import Head from "next/head";
import Navbar from "../../components/Navbar";
import SocialButton from "../../components/SocialButton";
import Github from "../../public/github.svg";
import Instagram from "../../public/instagram.svg";
import Linkedin from "../../public/linkedin.svg";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>JAI.DEV</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <section className="grid grid-cols-1 lg:grid-cols-[2fr_1fr] gap-4 mb-4">
        <div className="h-[30rem] rounded-3xl p-10 flex flex-col gap-16 bg-[url('../../public/gradient-bg.jpg')] bg-cover">
          <h1 className="text-4xl font-semibold">
            Hey! I'm Jai, a full-stack developer with a passion for innovation.
          </h1>
          <p className="flex-1">
            As a full-stack developer, I specialize in creating captivating web
            apps with functional back-ends
          </p>
          <div className="flex flex-col lg:flex-row items-center gap-4 justify-self-end">
            <button className=" bg-black text-white font-medium py-3 px-12 rounded-full w-60 lg:w-auto">
              Contact me
            </button>
            <div className="flex flex-row gap-5">
              <SocialButton bgColour="github">
                <Github />
              </SocialButton>
              <SocialButton bgColour="instagram">
                <Instagram />
              </SocialButton>
              <SocialButton bgColour="linkedin">
                <Linkedin />
              </SocialButton>
            </div>
          </div>
        </div>
        <div className="h-[30rem] rounded-3xl p-8 bg-[url('../../public/profile.jpg')] bg-cover bg-center">
          h
        </div>
      </section>
    </>
  );
}
